### ISSUE TITLE
Questions of the wiki text

### ISSUE THREAD

**Issue by Juanhui28** [TassAbdul/QZERO#1]
Dear authors,

Thanks for publishing the code! But seems there is one .txt file in the wiki folder. Is there any processed files available to download or do you have code to process the `enwiki-20230820-pages-articles-multistream.xml` file? Thank you!!

**Comment by TassAbdul** [comment]
Hi @Juanhui28,

Thank you for your interest in our work. I have added a [Jupyter notebook](https://github.com/rsinghlab/QZERO/blob/main/Prepare_wiki_dumps.ipynb) to show how we preprocess the files and a [link](https://drive.google.com/drive/folders/1hwUhcqI0I8k9x5t15XbIaWMKhm7d6NV3) to download the wiki files.
Please create a new issue if you have a new question. 
Thank you
